### ISSUE TITLE
Reach out to markdown-it

### ISSUE THREAD

**Issue by chrisjsewell** [ExecutableBookProject/markdown-it-py#2]
Once this is finalised (or before) we can reach out to the markdown-it guys so they can put it on their README (they already have a Ruby port listed).

We also may want to mention to the ReadtheDocs/nbconvert guys, who may be interested

**Comment by choldgraf** [comment]
Definitely - maybe before "finalized" but just after "it's good enough that we'd use it daily"?

for RTD - Eric was definitely interested in the conversation around CommonMark-compliant markdown parsers, and I think that if we had a really quality markdown parser for Python (in addition to the myst-parser for Sphinx) that we could convince them to start putting attention or resources into it.

**Comment by chrisjsewell** [comment]
It’s literally just #1 that is stopping me from saying it’s completely ready for daily use. Apart from that, there are 755 passing tests to back up my claim that it’s in full working condition 😁

**Comment by choldgraf** [comment]
you are a better code than I am @chrisjsewell 😆

**Comment by mmcky** [comment]
And me! :-)

**Comment by chrisjsewell** [comment]
markdown-it/markdown-it#658

**Comment by choldgraf** [comment]
nice! thanks for reaching out to them @chrisjsewell - shall we close this?

**Comment by chrisjsewell** [comment]
Yep, I also added it to https://github.com/commonmark/commonmark-spec/wiki/List-of-CommonMark-Implementations#python
