### ISSUE TITLE
Give us a runthrough of this package?

### ISSUE THREAD

**Issue by choldgraf** [ExecutableBookProject/markdown-it-py#3]
Hey @chrisjsewell - as you mentioned the API is pretty much going to remain static since it's mimicking markdown-it, wanna give us a quick runthrough of the major features and usage-patterns? Then I can try to add some short documentation if that helps...

**Comment by chrisjsewell** [comment]
Well obviously the main port of call is the README for this package and the documentation and live demo for markdown-it:
- https://github.com/markdown-it/markdown-it/blob/master/README.md
- https://markdown-it.github.io/ (click on the debug tab to see the AST)
- https://github.com/markdown-it/markdown-it/blob/master/docs/architecture.md

Every class / function name / variable for markdown-it-py is pretty exactly the same as their package, plus some syntatic sugar here and there to make it more pythonic, with `MarkdownIt` the main entry point and `Token` the singular 'AST' component (actually just a flat token stream):

Basic run:

```python
from markdown_it import MarkdownIt
md = MarkdownIt()
tokens = md.parse("some text")
text = md.render("some text")
```

Plugin/syntax selection:

```python
from markdown_it import MarkdownIt
from markdown_it.extensions.front_matter import front_matter_plugin
from markdown_it.extensions.footnote import footnote_plugin

md = (
    MarkdownIt()
    .use(front_matter_plugin)
    .use(footnote_plugin)
    .disable('image')
    .enable('table')
)
tokens = md.parse("some text")
text = md.render("some text")
```

Direct configuration:

```python
config = {
    "options": {
        "html": True,  # Enable HTML tags in source
        "xhtmlOut": True,  # Use '/' to close single tags (<br />)
        "breaks": False,  # Convert '\n' in paragraphs into <br>
        "langPrefix": "language-",  # CSS language prefix for fenced blocks
        "maxNesting": 20,  # Internal protection, recursion limit
    },
    "components": {
        "core": {"rules": ["normalize", "block", "inline"]},
        "block": {
            "rules": [
                "blockquote",
                "code",
                "fence",
                "heading",
                "hr",
                "html_block",
                "lheading",
                "list",
                "reference",
                "paragraph",
            ]
        },
        "inline": {
            "rules": [
                "autolink",
                "backticks",
                "emphasis",
                "entity",
                "escape",
                "html_inline",
                "image",
                "link",
                "newline",
                "text",
            ],
            "rules2": ["balance_pairs", "emphasis", "text_collapse"],
        },
    },
}

md = MarkdownIt(config)
md.render("text")
```

Plus look at the extension folder, on how to write a plugin, and how you insert/override render methods.

**Comment by chrisjsewell** [comment]
Yeh I'm not sure how much documentation we actually need, over and above pointing to the `markdown-it` documentation. I'll leave that for you to decide 😄 Note there is currently a docs folder already in the repo, but that's just left over from the original fork of markdown-it, so can be removed

**Comment by choldgraf** [comment]
So basically the `myst_parser` will define a `role_plugin` and `directive_plugin` etc, and we'll initialize the object w/ those at parse time?

And for controlling the rendering behavior (e.g., for HTML vs. docutils, is that also a plugin via call to `.enable`?)

**Comment by chrisjsewell** [comment]
See https://github.com/ExecutableBookProject/markdown-it-py/blob/master/try_running_renderer.py
and https://github.com/ExecutableBookProject/markdown-it-py/blob/50b23ad81be5f8d2471fc92937c4e6e8adc10885/markdown_it/doc_renderer.py#L76

You supply a renderer class to `Markdownit`, then the user / plugins can dynamically add custom render methods to it via `Markdownit.add_render_rule` (see the extensions).

The role plugin is already implemented (plus most of the other non-standard syntax). We don't necessarily need a directive plugin, just handle discriminating it  from a code fence at render time (as is done with mistletoe).

**Comment by chrisjsewell** [comment]
It’s an open question exactly how it will be used in the MyST-NB parser. It should be roughly the same as with mistletoe, in that you need to only do up to the ‘block rule’ parsing stage first, for each cell, and propagate internal state (e.g. collected ref definitions and footnotes). Then run post block rule stages on the full token list

**Comment by chrisjsewell** [comment]
This has now been added in https://github.com/ExecutableBookProject/markdown-it-py/blob/master/docs/Using_the_api.md
